title: Ateneu Popular do Montijo
description: Cultura, Educação e Comunidade em Montijo
lang: pt
theme: minimal-mistakes-jekyll

# GitHub Pages
url: "" # substituir pelo URL do GitHub Pages após publicação

# Plugins
plugins:
  - jekyll-seo-tag
